# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - xclip

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3

env:
  global:
    - DISPLAY=:99.0
    - _R_CHECK_FORCE_SUGGESTS_=false

r:
- 3.2
- 3.3
- oldrel
- devel

matrix:
  include:
  - r: 3.1
    warnings_are_errors: false
  - r: release
    env: DISPLAY=""
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - R CMD INSTALL .
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
