# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
env:
  - DISPLAY=:90.0
matrix:
  include:
  - r: release
    env: DISPLAY=""
sudo: false
cache: packages

addons:
  apt:
    packages:
      - xclip

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3

after_success:
  - Rscript -e 'covr::codecov()'
