# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - xclip

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3

env:
  global:
    - DISPLAY=:99.0
    - _R_CHECK_FORCE_SUGGESTS_=false

r:
  - 3.2
  - oldrel
  - release
  - devel

matrix:
  include:
  - r: 3.1
    warnings_are_errors: false
  - r: release
    env: DISPLAY=""
  - r: devel
    warnings_are_errors: false

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
